### ISSUE TITLE
splits was not adjusted on old data

### ISSUE THREAD

**Issue by tradewithmadhan** [BennyThadikaran/eod2#165] opened 2024-07-30 12:31 UTC
HI BennyThadikaran,
when i check old data come to know that stock splits was not adjusted ... Please check and fix if possible ..
Ex. TCS    
Jul 28, 2006 | 1/2 Stock Split
Jun 16, 2009 | 1/2 Stock Split
May 31, 2018 | 1/2 Stock Split

![image](https://github.com/user-attachments/assets/778b2746-2f7d-447e-9238-3104185b7b10)

**Comment by BennyThadikaran** [comment] 2024-07-31 04:10
Hi, I'm aware of this issue. The scripts written to compile EOD2 data were written some years back. EOD2 itself received many bug fixes but those fixes were not added to these scripts.

I completed updating the EOD2 compile scripts recently. Currently I'm working on moving the Corporate actions data from JSON files into Sqlite Db. This will make it faster to look up Ex Bonus / Split dates and verify if the adjustment was actioned successfully. It will also help in ongoing verification.

This might take another 2 weeks but will ensure the problem is fixed permanently. You can keep this issue open and will notify you once done.

**Comment by tradewithmadhan** [comment] 2024-07-31 06:13
Hi Benny,
Thanks for the update ...

**Comment by BennyThadikaran** [comment] 2024-08-05 14:23
@tradewithmadhan 

I have moved the corporate actions data into a DB and completed compiling the EOD2 data. I added some verification code to make sure all adjustments were made correctly. The dates you mentioned for TCS were also adjusted by the script.

I also managed to fix some bugs with the split / bonus which were not detected earlier. I need to update the fixes in EOD2 and merge this new data in eod2_data repo.

If no further issues come up, I will update both repos on Saturday. Thanks for reporting this issue. Always helps :smiley:

**Comment by BennyThadikaran** [comment] 2024-08-08 13:06
Its all done. You can follow the [update instructions here](https://github.com/BennyThadikaran/eod2/wiki/Installation#updating-the-git-repo) to get the latest update. Make sure to update both eod2 and eod2_data repo.

**Comment by BennyThadikaran** [comment] 2024-08-14 03:43
I am closing this issue for now. Let me know if there is any help you need.

**Closed by BennyThadikaran** 2024-08-14 03:43 UTC

**Comment by tradewithmadhan** [comment] 2024-08-14 05:53
Thanks BennyThadikaran, you can close it
